[providers.age]
type = "age"
recipients = [
    "age1nlqfv0ptcfs7ssuuq8c06nprslcvwg9qpt6kf0ex20jhnknjmsqsrqf96k", # Sasha's PC WSL2
    "age1ayemh9gkd9p70wta8ewqd8xepr5p2293c46wkq2n9jagzhqd0v9q8txja9", # Sasha's MacBook Air M2
    "age1jm5g49tr96kf9qfhwurpkp3f6npucueec4q065pzrqux73d5qe0skawf43", # Sasha's MacBook Pro M1 Pro
    "age198ynsd3sfwlyhv5s2t06gxgxssgs24l9pyuluylu2tsmyhyrh5xs7he9uh", # Josh MacBook
]

[secrets.FONTAWESOME_PACKAGE_TOKEN]
description = "Font Awesome npm token"
provider = "age"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MGxtWTE2TEpkRkdiSE5SVzV0bnd0YVpDRVRoMThQOENvM2tmb3dSVUhJCjROTzJQYUlKRmxOenRHRW5qcHBQcEJhTWFDUmhsYzE2bGMraUplMkFCWEUKLT4gWDI1NTE5IDZOT094OHVKdy9JL04za2ZxTmpiSFgwbXRIWVZHcjJiVUtCdWZZSGZVMkEKZzdlODlSV2hTZzVNSDh1STN0KzVuaGF6UVF4U2QvY24vTHB4amY2VkFJZwotPiBYMjU1MTkgNGhFWFNvUkM0ZTNDQ0xIckxDUTVmem5WZWlSdXhnQ1d6YUdSWHEyQWl6TQo3TjIwU2RoQ0VuN1gxaVVWMTNjRVR5d3lleFJMejRkZUdDYTRYUjBQSkVZCi0+IFgyNTUxOSAwR0NvL3U5WERUTnNrTkZQSVJJajB3WjRFdEhZRUNRcTRua2RTZ1QzcXg4Ck5HWURYa3M5NVliUFFzdlhpd01WNHVTbUVlTFU5RWR6M2d1RkR0Zmp3YWcKLS0tIE5sbHE2MUlJSitycnBTR0RhbXpySlgyaWVBclBpVG0wNmxzS091cFV5alkKWNy4bUMn40dz2T/+lqK+D/fLTPfs+IZ/qrYZYEFvUP1blHqCvgxTOsOcqt5mnRUZGMMC28syBkqHqNxBx0blfY8hlas="

[secrets.VERCEL_GATEWAY_KEY]
description = "Vercel Gateway key"
provider = "age"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ckFxbGxPMlUrNHY0WkNoTHkrbjlNUUtVV0tZMGQ4SkVYY1dLL21GNndZCkI1NmI5WUhlYTlpeFhiNFVldFQ0WE9xSHYxMUd1aVVodTJEYzJieFlOTFEKLT4gWDI1NTE5IE1jK1JSN1JIeldHekdhblNSSlM3NVFrZzhWMnI5U3k0WkRTRWh0Z3ZtM3cKdlg2c1d1Q2dYc3BHWlVWcFNGS2VVVU04a0Rlb2dua0R1VnRVSlV0Vk00bwotPiBYMjU1MTkgc0FjdWVtZGJDV3M0TERLUmFYRDEwV2RhRmhBS3pYUC9pRFdNMkFJR3ZqUQpOVjJJbWR3V0toa2FFLzEvSXNSVytXZHFJaWxqVEFrcFp3T3BSZ1VGQzdNCi0+IFgyNTUxOSBpVy9VVG9XZ3U4VG0vbHJLb095MnlxK01iOFVkQ1ZKSnA1eEw0V1VuWlNvCjlCR1RmS2g2QURIdXNUUUNXT29Ddkl5M0IyQXlJSXJLenpPMkNmOGhkU3MKLS0tIGl6bEttKzBrSTVXUFJEZk4zU1VOM0h3MjhBM1NLUEpuOUErRGxvazE3d2cKx2hGBSXsQyJDd16d+/WlwdBwzwlvRpRZ2FuuyUSUt8BWkMIVn7EwqL7FbP/MnFZH6q9OMQ2VoVnDodi0pOg6b1I+PRcd++Az+gW8w+uo+UytJUMfzYQK/zXrVag="
