[providers.age]
type = "age"
recipients = [
    "age1nlqfv0ptcfs7ssuuq8c06nprslcvwg9qpt6kf0ex20jhnknjmsqsrqf96k", # Sasha's PC WSL2
    "age1ayemh9gkd9p70wta8ewqd8xepr5p2293c46wkq2n9jagzhqd0v9q8txja9", # Sasha's MacBook Air M2
    "age1jm5g49tr96kf9qfhwurpkp3f6npucueec4q065pzrqux73d5qe0skawf43", # Sasha's MacBook Pro M1 Pro
]

[secrets.FONTAWESOME_PACKAGE_TOKEN]
description = "Font Awesome npm token"
provider = "age"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDME9NUE0zMEkvNnVYRnd5SEl2c0JIOEU4UlVmUXRmMjR0N3I5QXlob1VRCkV5Wjhnd1pRMGgxVkpUa1dzTzhzdHpGV2lvL1hvUHhxSVYyOE5aN3ZpNmsKLT4gWDI1NTE5IGRubFMwNE5hc1ozdWNrL1o1WFUvUVZ5SnJKb08yVmVJRmtWa0pFbVdqa0UKYk8zKzU2NTRUVnZCLzNnTzFkc3lobXBkYk5ZUElJZGdMQm8zTlQyVWlmbwotPiBYMjU1MTkgL282ZmJRNjBuOTJiSitwd1BFT1VzMm4wZG5HK1pHSXVzeXhUZFRiTG54TQo4a1hDdHB3K294N3dnOGFXeWpmbW9QbkJTU2s0aUZLRnpQU01QQUpiSTRVCi0tLSBib3dqOFhEM3lKOU5XVVlNT2NZcFhnMGV1VXpaNU83QnA2aFo0SjF1eDRJCnl5N33Xdt7OPpNKyzJGApES6CDPw/xPZNyptJ1dvX75wI1Z4Y+cSsTuZwiAEUL4e6JvLBtqcdwDZYDOuMgXH8vs+oSR"

[secrets.VERCEL_GATEWAY_KEY]
description = "Vercel Gateway key"
provider = "age"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZTl4WGNpUXdubVhmZnJJM3IybkxlUXFKQWowM2NpVHgrS09ISW1aRFFBCk1NaFR4RDV4bk9taUczb1M3b3VhUWZ5MFJtWGUyQWVXVlBOdXVoSnJKZzAKLT4gWDI1NTE5IDlwVGFDdHVoZmNyc1FYWHdRM0Jxa2swSTRhdkFIVlRHOWtpM0UrcWhoa1EKajU4TGVuK1NwSGtBVDUzd3VabU5BMHl5VlJjSUdnUExLMThSVGluWFV5ZwotPiBYMjU1MTkgcklkQllzalE1bUJKRjNLUGpnRjFJRnhhMmNnUjhWQ3pqSTF5Ti9iUHNTSQo2eXZXOWpXdDBPaFpLUUp3RlJ4Q3JyWENTWGg0RmlDd1lZSUhnaDZjMUU0Ci0tLSBlOVpIdEhpMjdMbnpqcHp6bFRIUzJIZ28zUVJRNFRqSHVPMko2aDRhQk5RCrreFlT2f5DLWXIqqdBL5DAC7RyiTYUskNIIMT7PNZFpr8hNlnapD3myyxget+EF6H/zAkxO3aH0gO1IDI0+PUnjNz6mceTumK9Im9qYWzLDGA4x6BP6Ltj24dMe"
