[providers.age]
type = "age"
recipients = [
  "age1ayemh9gkd9p70wta8ewqd8xepr5p2293c46wkq2n9jagzhqd0v9q8txja9", # Sasha's MacBook Air M2
  "age1jm5g49tr96kf9qfhwurpkp3f6npucueec4q065pzrqux73d5qe0skawf43", # Sasha's MacBook Pro M1 Pro
]

[secrets.FONTAWESOME_PACKAGE_TOKEN]
description = "Font Awesome npm token"
provider = "age"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT2JsSXROMzJoeHdOdUpGdzdMLzgzSnlqYllOcW5MSW1WODdCVjRndG53CjR6T1cvM0xQOXFmcUhHaElES0RMNDcrQUsvM1lKTElOaU9YMWpKNGN6WXMKLT4gWDI1NTE5IFBHMDIrcmpmSmJ3ODNYbWZ4bEF6QmVmdUtlVkM5ank0UEthOVBhamNoQUUKdHNPb1dReDc4Y0d3QkRhYkFwbUVkRkMrYkEwdDdjS0pwcUxKTXo0SUV4WQotLS0gOW5sTXlnS2FCclY1M1JSTVJxRGhhenBadVVRb0FzSkhWdUp4K1dCSFR1cwpig7Zxy5OUWMVCNP1gz47bF6f1umH23SWC5q8f1nPsCHI/sd3e5RTiCDQPoXMKoUqXRlxRhF2g7uxSNF/uRIfvbnSyww=="

[secrets.VERCEL_GATEWAY_KEY]
description = "Vercel Gateway key"
provider = "age"
value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTlp6ckR2dlZhbzgwTU1WaFcxUVdPMnJqTnUzS1NkVFJVSjZKSUlLNldZCnk3VXN1cHdUVks2cDRxZW44a2FoY1BocEN6cHhJZ21JRENpYjF3c0RNZ3cKLT4gWDI1NTE5IEI0VDZLN3lWT056MUtvUkhnSWl5MEEyb3VONEpUWFR6QXBwclJqSEFJSFEKYXo0RHp6Yk1yOGQ2c0ttaG1JTlhRVmY5SkdGQW52c1NuY1BxM1B3elErVQotLS0gZDZPdC9JRC9admNrWlBRczNoMEhGVENDTUVjOVU3THFRQTBvWElPL25SYwr6Fntajbqz2C7VVgArdcT2RAL5oo/P+L4TNyZb7289yFQ/1Zn//S0WrhI0R5G5bfoV8kk6ATu9TDrEgvtC1AO2mvzR+xwtDxbjmoE7D9Y45UGf8Y7YnI4n4bbKTQ=="
