#:schema node_modules/wrangler/config-schema.json
name = "mindrig-home"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-10-27"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = false

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
