[package]
name = "mindcontrol_code_parser"
description = "Mind Control Code parser"
version = "0.1.0"
edition = "2024"
license = "UNLICENSED"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0.219"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.100"
