name = "wrkspc-types"
root = ""
out = "pkgs"
src = "src"
entry = "**/*.type"

[ts]
enabled = true
out = "ts"

[ts.manifest]
name = "@mindrig/types"
version = "0.1.0"
license = "FSL-1.1-ALv2"

[rs]
derive = ["Debug", "Clone", "PartialEq"]
enabled = true
out = "rs"

[rs.manifest]

[rs.manifest.package]
name = "mindrig_types"
version = "0.1.0"
license = "FSL-1.1-ALv2"
edition = "2024"
